services:
  postgresdb:
    container_name: postgresqldb
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  local_pgdata:
    driver: local      



