server:
  forward-headers-strategy: framework
  port: 9090

spring:
  application:
    name: oauth2-idp
  
  threads:
    virtual:
      enabled: true

  security:
    # user:
    #   name: user1
    #   password: "{bcrypt}$2a$10$v03OSTB3Ud2uxyhmypic/uCJ9SQlyu5YWvm5of9EQ9SJzCbw4VgKC"
    #   roles: USER, READER,ADMIN

    oauth2:
      authorizationserver:
        client:
          client-1:
            require-authorization-consent: true
            registration:
              client-id: "client"
              # the client secret is "secret" (without quotes)
              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              scopes:
                - "openid"
                - "profile"
                - "message.read"
                - "message.write"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/client"
              post-logout-redirect-uris:
                - "http://localhost:8080/"
              

logging:  
  # pattern:
  #   console: "%d %-5level [%thread] %logger{80}.%M\\(%line\\): %msg%n"
    # file: "%d %-5level [%thread] %logger{40}: %msg%n"


  level:
    root: INFO
    org.springframework.security: TRACE